version: "3"

services:
  node_one:
    image: kvex:latest
    container_name: node_one
    environment:
      ID: "50"
      PORT: "4000"
      NODES: "51:172.20.0.6:4000,52:172.20.0.7:4000"
      TIMER: "1500"
    build:
      dockerfile: Dockerfile
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.20.0.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/admin/adaptive/raft-kotlin/logs:/logs
    working_dir: /usr/src/app

  node_two:
    image: kvex:latest
    container_name: node_two
    environment:
      ID: "51"
      PORT: "4000"
      NODES: "50:172.20.0.5:4000,52:172.20.0.7:4000"
      TIMER: "1450"
    build:
      dockerfile: Dockerfile
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.20.0.6
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/admin/adaptive/raft-kotlin/logs:/logs
    working_dir: /usr/src/app

  node_three:
    image: kvex:latest
    container_name: node_three
    environment:
      ID: "52"
      PORT: "4000"
      NODES: "50:172.20.0.5:4000,51:172.20.0.6:4000"
      TIMER: "1550"
    build:
      dockerfile: Dockerfile
      context: .
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 172.20.0.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/admin/adaptive/raft-kotlin/logs:/logs
    working_dir: /usr/src/app


networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
